package com.spear.home.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class MainPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private TabSheet tabSheet_3;
	@AutoGenerated
	private VerticalLayout photosVerticalLayout;
	@AutoGenerated
	private VerticalLayout streamVerticalLayout;
	@AutoGenerated
	private VerticalLayout controlVerticalLayout;
	@AutoGenerated
	private Button toggleAlarmButton;
	@AutoGenerated
	private Label statusLabel;
	@AutoGenerated
	private Label homeMonitoringLabel;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	

	public VerticalLayout getPhotosVerticalLayout() {
		return photosVerticalLayout;
	}



	public Embedded getEmbeddedImage() {
		return embeddedImage;
	}



	public VerticalLayout getStreamVerticalLayout() {
		return streamVerticalLayout;
	}



	public VerticalLayout getControlVerticalLayout() {
		return controlVerticalLayout;
	}



	public Button getToggleAlarmButton() {
		return toggleAlarmButton;
	}



	public Label getStatusLabel() {
		return statusLabel;
	}



	public Label getHomeMonitoringLabel() {
		return homeMonitoringLabel;
	}



	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		mainLayout.setComponentAlignment(panel_1, new Alignment(20));
		
		return mainLayout;
	}



	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}



	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// homeMonitoringLabel
		homeMonitoringLabel = new Label();
		homeMonitoringLabel.setImmediate(false);
		homeMonitoringLabel.setWidth("-1px");
		homeMonitoringLabel.setHeight("-1px");
		homeMonitoringLabel.setValue("Home Monitoring");
		verticalLayout_2.addComponent(homeMonitoringLabel);
		verticalLayout_2.setComponentAlignment(homeMonitoringLabel,
				new Alignment(20));
		
		// statusLabel
		statusLabel = new Label();
		statusLabel.setImmediate(false);
		statusLabel.setWidth("-1px");
		statusLabel.setHeight("-1px");
		statusLabel.setValue("Label");
		verticalLayout_2.addComponent(statusLabel);
		verticalLayout_2.setComponentAlignment(statusLabel, new Alignment(20));
		
		// tabSheet_3
		tabSheet_3 = buildTabSheet_3();
		verticalLayout_2.addComponent(tabSheet_3);
		verticalLayout_2.setExpandRatio(tabSheet_3, 1.0f);
		verticalLayout_2.setComponentAlignment(tabSheet_3, new Alignment(20));
		
		return verticalLayout_2;
	}



	@AutoGenerated
	private TabSheet buildTabSheet_3() {
		// common part: create layout
		tabSheet_3 = new TabSheet();
		tabSheet_3.setImmediate(true);
		tabSheet_3.setWidth("100.0%");
		tabSheet_3.setHeight("100.0%");
		
		// controlVerticalLayout
		controlVerticalLayout = buildControlVerticalLayout();
		tabSheet_3.addTab(controlVerticalLayout, "Control", null);
		
		// streamVerticalLayout
		streamVerticalLayout = new VerticalLayout();
		streamVerticalLayout.setImmediate(false);
		streamVerticalLayout.setWidth("100.0%");
		streamVerticalLayout.setHeight("100.0%");
		streamVerticalLayout.setMargin(false);
		tabSheet_3.addTab(streamVerticalLayout, "Live Stream", null);
		
		// photosVerticalLayout
		photosVerticalLayout = new VerticalLayout();
		photosVerticalLayout.setImmediate(false);
		photosVerticalLayout.setWidth("-1px");
		photosVerticalLayout.setHeight("-1px");
		photosVerticalLayout.setMargin(false);
		tabSheet_3.addTab(photosVerticalLayout, "Recent Photos", null);
		
		return tabSheet_3;
	}



	@AutoGenerated
	private VerticalLayout buildControlVerticalLayout() {
		// common part: create layout
		controlVerticalLayout = new VerticalLayout();
		controlVerticalLayout.setImmediate(false);
		controlVerticalLayout.setWidth("100.0%");
		controlVerticalLayout.setHeight("100.0%");
		controlVerticalLayout.setMargin(true);
		
		// toggleAlarmButton
		toggleAlarmButton = new Button();
		toggleAlarmButton.setCaption("Button");
		toggleAlarmButton.setImmediate(true);
		toggleAlarmButton.setWidth("-1px");
		toggleAlarmButton.setHeight("-1px");
		controlVerticalLayout.addComponent(toggleAlarmButton);
		controlVerticalLayout.setComponentAlignment(toggleAlarmButton,
				new Alignment(48));
		
		return controlVerticalLayout;
	}

}
